### ISSUE TITLE
Repository is over data quota. Move data to Zenodo?

### ISSUE THREAD

**Issue by r03ert0** [gdevenyi/AllenHumanGeneMNI#4]
Hello!
I tried to clone the repo today, but it seems GitHub wants your money or it will not work:

```
$ git clone https://github.com/gdevenyi/AllenHumanGeneMNI.git
Cloning into 'AllenHumanGeneMNI'...
remote: Enumerating objects: 133, done.
remote: Total 133 (delta 0), reused 0 (delta 0), pack-reused 133
Receiving objects: 100% (133/133), 671.67 KiB | 311.00 KiB/s, done.
Resolving deltas: 100% (25/25), done.
Downloading registrations/class123/H0351.1009_t1.nii.gz-model_extracted_t1.nii.gz1InverseWarp.nii.gz (184 MB)
Error downloading object: registrations/class123/H0351.1009_t1.nii.gz-model_extracted_t1.nii.gz1InverseWarp.nii.gz (c5a748a): Smudge error: Error downloading registrations/class123/H0351.1009_t1.nii.gz-model_extracted_t1.nii.gz1InverseWarp.nii.gz (c5a748a74f6b9e5c21b423e4a8648ec204c240c20f3b50f75d2b3559cff83cea): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
```

Maybe a (free) solution would be to move the data to Zenodo.org? Additionally, you would get a DOI for your data, which people could cite in their papers. If you upload the files individually (instead of in a single big .zip blob) it would be possible to download them as needed from scripts.

**Comment by gdevenyi** [comment]
Great idea thanks :)

My primary use as (as well as everyone else's I worked with) were the MNI coordinate points in the *csv at https://github.com/gdevenyi/AllenHumanGeneMNI/tree/master/transformed-points/recombine so when I ran into issues uploading I gave up. I'll get this packed up and onto a Zenodo dataset.

**Comment by r03ert0** [comment]
ok, thank you! I was just worried when I saw the error message :p

**Comment by gdevenyi** [comment]
I updated the zenodo record I already had with a zipfile of the entire git repo: https://zenodo.org/record/3677132

**Comment by r03ert0** [comment]
awesome! thank you :D

**Comment by gdevenyi** [comment]
Please note the other issues in the repo, contributions are welcome!
