### ISSUE TITLE
Add LICENSE file

### ISSUE THREAD

**Issue by rmarkello** [gdevenyi/AllenHumanGeneMNI#5]
Hi @gdevenyi !

Thanks so much for making this resource available ! I was hoping you might be willing to add an OS-permissive license to the repo so that its contents can be re-used (with appropriate acknowledgement) in other tools (e.g., rmarkello/abagen#148).

Let me know if you have a preference for license—happy to open a PR adding LICENSE file (e.g., MIT, BSD-3, Apache 2.0, etc.).

**Comment by gdevenyi** [comment]
Sure, I can look into a licence, but I think it needs to be compaitable with the Allen's terms:
https://alleninstitute.org/legal/terms-use/

At first glance the commercial-ok licences don't seem to be so, but I have to check closer.

**Comment by gdevenyi** [comment]
Fixed by 73d1e643fcbeb1989d4882b9ed35d883497b9b05
